[fi6130]
device = "fujitsu:fi-6130dj:446340"
sensors = "hardware"

[fi6130.actions.AutoScan]
page-loaded = "yes"
function = "5"

[fi6130.actions.scan_F1]
# scan einseitig und in Farbe als PDF
page-loaded = "yes"
scan = "yes"
function = "1"

[fi6130.actions.scan_F2]
# Scan doppelseitig und in Farbe als PDF
page-loaded = "yes"
scan = "yes"
function = "2"

[fi6130.commandos]
AutoScan = "cmdAuto"
scan_F1 = 'scanimage --progress --verbose --format="pdf" --source="ADF Duplex" --batch="/home/pi/paperless-ngx/consume/[date].pdf" --page-width="210" --resolution="300" --page-height="297" --mode="Color"'
scan_f2 = "cmdScanF2"

